<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_biller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_biller_model');
    } 

    /*
     * Listing of tb_biller
     */
    function index()
    {
        $data['tb_biller'] = $this->Tb_biller_model->get_all_tb_biller();
        
        $data['_view'] = 'tb_biller/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_biller
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'col_status' => $this->input->post('col_status'),
				'col_code' => $this->input->post('col_code'),
            );
            
            $tb_biller_id = $this->Tb_biller_model->add_tb_biller($params);
            redirect('tb_biller/index');
        }
        else
        {            
            $data['_view'] = 'tb_biller/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_biller
     */
    function edit($col_name)
    {   
        // check if the tb_biller exists before trying to edit it
        $data['tb_biller'] = $this->Tb_biller_model->get_tb_biller($col_name);
        
        if(isset($data['tb_biller']['col_name']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'col_status' => $this->input->post('col_status'),
					'col_code' => $this->input->post('col_code'),
                );

                $this->Tb_biller_model->update_tb_biller($col_name,$params);            
                redirect('tb_biller/index');
            }
            else
            {
                $data['_view'] = 'tb_biller/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_biller you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_biller
     */
    function remove($col_name)
    {
        $tb_biller = $this->Tb_biller_model->get_tb_biller($col_name);

        // check if the tb_biller exists before trying to delete it
        if(isset($tb_biller['col_name']))
        {
            $this->Tb_biller_model->delete_tb_biller($col_name);
            redirect('tb_biller/index');
        }
        else
            show_error('The tb_biller you are trying to delete does not exist.');
    }
    
}
