<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_paidtxn extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_paidtxn_model');
    } 

    /*
     * Listing of tb_paidtxn
     */
    function index()
    {
        $data['tb_paidtxn'] = $this->Tb_paidtxn_model->get_all_tb_paidtxn();
        
        $data['_view'] = 'tb_paidtxn/index';
        $this->load->view('layouts/main',$data);
    }
}
