<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_privilege extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_privilege_model');
    } 

    /*
     * Listing of tb_privileges
     */
    function index()
    {
        $data['tb_privileges'] = $this->Tb_privilege_model->get_all_tb_privileges();
        
        $data['_view'] = 'tb_privilege/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_privilege
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'p_service' => $this->input->post('p_service'),
				'p_partnerid' => $this->input->post('p_partnerid'),
				'p_status' => $this->input->post('p_status'),
            );
            
            $tb_privilege_id = $this->Tb_privilege_model->add_tb_privilege($params);
            redirect('tb_privilege/index');
        }
        else
        {
			$this->load->model('Tb_service_model');
			$data['all_tb_service'] = $this->Tb_service_model->get_all_tb_service();
            
            $data['_view'] = 'tb_privilege/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_privilege
     */
    function edit($p_id)
    {   
        // check if the tb_privilege exists before trying to edit it
        $data['tb_privilege'] = $this->Tb_privilege_model->get_tb_privilege($p_id);
        
        if(isset($data['tb_privilege']['p_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'p_service' => $this->input->post('p_service'),
					'p_partnerid' => $this->input->post('p_partnerid'),
					'p_status' => $this->input->post('p_status'),
                );

                $this->Tb_privilege_model->update_tb_privilege($p_id,$params);            
                redirect('tb_privilege/index');
            }
            else
            {
				$this->load->model('Tb_service_model');
				$data['all_tb_service'] = $this->Tb_service_model->get_all_tb_service();

                $data['_view'] = 'tb_privilege/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_privilege you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_privilege
     */
    function remove($p_id)
    {
        $tb_privilege = $this->Tb_privilege_model->get_tb_privilege($p_id);

        // check if the tb_privilege exists before trying to delete it
        if(isset($tb_privilege['p_id']))
        {
            $this->Tb_privilege_model->delete_tb_privilege($p_id);
            redirect('tb_privilege/index');
        }
        else
            show_error('The tb_privilege you are trying to delete does not exist.');
    }
    
}
