<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_partner extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_partner_model');
    } 

    /*
     * Listing of tb_partner
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_partner/index?');
        $config['total_rows'] = $this->Tb_partner_model->get_all_tb_partner_count();
        $this->pagination->initialize($config);

        $data['tb_partner'] = $this->Tb_partner_model->get_all_tb_partner($params);
        
        $data['_view'] = 'tb_partner/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_partner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'col_status' => $this->input->post('col_status'),
				'col_name' => $this->input->post('col_name'),
				'col_ip' => $this->input->post('col_ip'),
				'col_date' => $this->input->post('col_date'),
				'col_login' => $this->input->post('col_login'),
            );
            
            $tb_partner_id = $this->Tb_partner_model->add_tb_partner($params);
            redirect('tb_partner/index');
        }
        else
        {            
            $data['_view'] = 'tb_partner/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_partner
     */
    function edit($col_id)
    {   
        // check if the tb_partner exists before trying to edit it
        $data['tb_partner'] = $this->Tb_partner_model->get_tb_partner($col_id);
        
        if(isset($data['tb_partner']['col_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'col_status' => $this->input->post('col_status'),
					'col_name' => $this->input->post('col_name'),
					'col_ip' => $this->input->post('col_ip'),
					'col_date' => $this->input->post('col_date'),
					'col_login' => $this->input->post('col_login'),
                );

                $this->Tb_partner_model->update_tb_partner($col_id,$params);            
                redirect('tb_partner/index');
            }
            else
            {
                $data['_view'] = 'tb_partner/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_partner you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_partner
     */
    function remove($col_id)
    {
        $tb_partner = $this->Tb_partner_model->get_tb_partner($col_id);

        // check if the tb_partner exists before trying to delete it
        if(isset($tb_partner['col_id']))
        {
            $this->Tb_partner_model->delete_tb_partner($col_id);
            redirect('tb_partner/index');
        }
        else
            show_error('The tb_partner you are trying to delete does not exist.');
    }
    
}
