<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_request extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_request_model');
    } 

    /*
     * Listing of tb_request
     */
    function index()
    {
        $data['tb_request'] = $this->Tb_request_model->get_all_tb_request();
        
        $data['_view'] = 'tb_request/index';
        $this->load->view('layouts/main',$data);
    }
}
