<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_service extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_service_model');
    } 

    /*
     * Listing of tb_service
     */
    function index()
    {
        $data['tb_service'] = $this->Tb_service_model->get_all_tb_service();
        
        $data['_view'] = 'tb_service/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_service
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'col_name' => $this->input->post('col_name'),
				'col_description' => $this->input->post('col_description'),
				'col_status' => $this->input->post('col_status'),
            );
            
            $tb_service_id = $this->Tb_service_model->add_tb_service($params);
            redirect('tb_service/index');
        }
        else
        {            
            $data['_view'] = 'tb_service/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_service
     */
    function edit($col_id)
    {   
        // check if the tb_service exists before trying to edit it
        $data['tb_service'] = $this->Tb_service_model->get_tb_service($col_id);
        
        if(isset($data['tb_service']['col_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'col_name' => $this->input->post('col_name'),
					'col_description' => $this->input->post('col_description'),
					'col_status' => $this->input->post('col_status'),
                );

                $this->Tb_service_model->update_tb_service($col_id,$params);            
                redirect('tb_service/index');
            }
            else
            {
                $data['_view'] = 'tb_service/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_service you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_service
     */
    function remove($col_id)
    {
        $tb_service = $this->Tb_service_model->get_tb_service($col_id);

        // check if the tb_service exists before trying to delete it
        if(isset($tb_service['col_id']))
        {
            $this->Tb_service_model->delete_tb_service($col_id);
            redirect('tb_service/index');
        }
        else
            show_error('The tb_service you are trying to delete does not exist.');
    }
    
}
