<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_timeout extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_timeout_model');
    } 

    /*
     * Listing of tb_timeout
     */
    function index()
    {
        $data['tb_timeout'] = $this->Tb_timeout_model->get_all_tb_timeout();
        
        $data['_view'] = 'tb_timeout/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_timeout
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'col_use_timeout' => $this->input->post('col_use_timeout'),
				'col_timeout' => $this->input->post('col_timeout'),
            );
            
            $tb_timeout_id = $this->Tb_timeout_model->add_tb_timeout($params);
            redirect('tb_timeout/index');
        }
        else
        {            
            $data['_view'] = 'tb_timeout/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_timeout
     */
    function edit($col_partner_id)
    {   
        // check if the tb_timeout exists before trying to edit it
        $data['tb_timeout'] = $this->Tb_timeout_model->get_tb_timeout($col_partner_id);
        
        if(isset($data['tb_timeout']['col_partner_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'col_use_timeout' => $this->input->post('col_use_timeout'),
					'col_timeout' => $this->input->post('col_timeout'),
                );

                $this->Tb_timeout_model->update_tb_timeout($col_partner_id,$params);            
                redirect('tb_timeout/index');
            }
            else
            {
                $data['_view'] = 'tb_timeout/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_timeout you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_timeout
     */
    function remove($col_partner_id)
    {
        $tb_timeout = $this->Tb_timeout_model->get_tb_timeout($col_partner_id);

        // check if the tb_timeout exists before trying to delete it
        if(isset($tb_timeout['col_partner_id']))
        {
            $this->Tb_timeout_model->delete_tb_timeout($col_partner_id);
            redirect('tb_timeout/index');
        }
        else
            show_error('The tb_timeout you are trying to delete does not exist.');
    }
    
}
