<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_biller_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_biller by col_name
     */
    function get_tb_biller($col_name)
    {
        return $this->db->get_where('tb_biller',array('col_name'=>$col_name))->row_array();
    }
        
    /*
     * Get all tb_biller
     */
    function get_all_tb_biller()
    {
        $this->db->order_by('col_name', 'desc');
        return $this->db->get('tb_biller')->result_array();
    }
        
    /*
     * function to add new tb_biller
     */
    function add_tb_biller($params)
    {
        $this->db->insert('tb_biller',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_biller
     */
    function update_tb_biller($col_name,$params)
    {
        $this->db->where('col_name',$col_name);
        return $this->db->update('tb_biller',$params);
    }
    
    /*
     * function to delete tb_biller
     */
    function delete_tb_biller($col_name)
    {
        return $this->db->delete('tb_biller',array('col_name'=>$col_name));
    }
}
