<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_bill_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_bill by col_id
     */
    function get_tb_bill($col_id)
    {
        return $this->db->get_where('tb_bill',array('col_id'=>$col_id))->row_array();
    }
        
    /*
     * Get all tb_bill
     */
    function get_all_tb_bill()
    {
        $this->db->order_by('col_id', 'desc');
        return $this->db->get('tb_bill')->result_array();
    }
        
    /*
     * function to add new tb_bill
     */
    function add_tb_bill($params)
    {
        $this->db->insert('tb_bill',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_bill
     */
    function update_tb_bill($col_id,$params)
    {
        $this->db->where('col_id',$col_id);
        return $this->db->update('tb_bill',$params);
    }
    
    /*
     * function to delete tb_bill
     */
    function delete_tb_bill($col_id)
    {
        return $this->db->delete('tb_bill',array('col_id'=>$col_id));
    }
}
