<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_privilege_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_privilege by p_id
     */
    function get_tb_privilege($p_id)
    {
        return $this->db->get_where('tb_privileges',array('p_id'=>$p_id))->row_array();
    }
        
    /*
     * Get all tb_privileges
     */
    function get_all_tb_privileges()
    {
        $this->db->order_by('p_id', 'desc');
        return $this->db->get('tb_privileges')->result_array();
    }
        
    /*
     * function to add new tb_privilege
     */
    function add_tb_privilege($params)
    {
        $this->db->insert('tb_privileges',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_privilege
     */
    function update_tb_privilege($p_id,$params)
    {
        $this->db->where('p_id',$p_id);
        return $this->db->update('tb_privileges',$params);
    }
    
    /*
     * function to delete tb_privilege
     */
    function delete_tb_privilege($p_id)
    {
        return $this->db->delete('tb_privileges',array('p_id'=>$p_id));
    }
}
