<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_partnerkey_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_partnerkey by id
     */
    function get_tb_partnerkey($id)
    {
        return $this->db->get_where('tb_partnerkey',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_partnerkey
     */
    function get_all_tb_partnerkey()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_partnerkey')->result_array();
    }
        
    /*
     * function to add new tb_partnerkey
     */
    function add_tb_partnerkey($params)
    {
        $this->db->insert('tb_partnerkey',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_partnerkey
     */
    function update_tb_partnerkey($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_partnerkey',$params);
    }
    
    /*
     * function to delete tb_partnerkey
     */
    function delete_tb_partnerkey($id)
    {
        return $this->db->delete('tb_partnerkey',array('id'=>$id));
    }
}
