<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_request_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_request by r_id
     */
    function get_tb_request($r_id)
    {
        return $this->db->get_where('tb_request',array('r_id'=>$r_id))->row_array();
    }
        
    /*
     * Get all tb_request
     */
    function get_all_tb_request()
    {
        $this->db->order_by('r_id', 'desc');
        return $this->db->get('tb_request')->result_array();
    }
        
    /*
     * function to add new tb_request
     */
    function add_tb_request($params)
    {
        $this->db->insert('tb_request',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_request
     */
    function update_tb_request($r_id,$params)
    {
        $this->db->where('r_id',$r_id);
        return $this->db->update('tb_request',$params);
    }
    
    /*
     * function to delete tb_request
     */
    function delete_tb_request($r_id)
    {
        return $this->db->delete('tb_request',array('r_id'=>$r_id));
    }
}
