<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_recvmoney_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_recvmoney by id
     */
    function get_tb_recvmoney($id)
    {
        return $this->db->get_where('tb_recvmoney',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_recvmoney
     */
    function get_all_tb_recvmoney()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_recvmoney')->result_array();
    }
        
    /*
     * function to add new tb_recvmoney
     */
    function add_tb_recvmoney($params)
    {
        $this->db->insert('tb_recvmoney',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_recvmoney
     */
    function update_tb_recvmoney($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_recvmoney',$params);
    }
    
    /*
     * function to delete tb_recvmoney
     */
    function delete_tb_recvmoney($id)
    {
        return $this->db->delete('tb_recvmoney',array('id'=>$id));
    }
}
