<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_service by col_id
     */
    function get_tb_service($col_id)
    {
        return $this->db->get_where('tb_service',array('col_id'=>$col_id))->row_array();
    }
        
    /*
     * Get all tb_service
     */
    function get_all_tb_service()
    {
        $this->db->order_by('col_id', 'desc');
        return $this->db->get('tb_service')->result_array();
    }
        
    /*
     * function to add new tb_service
     */
    function add_tb_service($params)
    {
        $this->db->insert('tb_service',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_service
     */
    function update_tb_service($col_id,$params)
    {
        $this->db->where('col_id',$col_id);
        return $this->db->update('tb_service',$params);
    }
    
    /*
     * function to delete tb_service
     */
    function delete_tb_service($col_id)
    {
        return $this->db->delete('tb_service',array('col_id'=>$col_id));
    }
}
